// Error codes for the Print Agent

module.exports = {
  // Printer errors
  PRINTER_OFFLINE: 'PRINTER_OFFLINE',
  PRINTER_NOT_FOUND: 'PRINTER_NOT_FOUND',
  PRINTER_NOT_CONFIGURED: 'PRINTER_NOT_CONFIGURED',

  // Print job errors
  PRINT_FAILED: 'PRINT_FAILED',
  INVALID_DATA: 'INVALID_DATA',
  INVALID_TYPE: 'INVALID_TYPE',
  INVALID_REQUEST: 'INVALID_REQUEST',

  // System errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFIG_ERROR: 'CONFIG_ERROR',
  ACCESS_DENIED: 'ACCESS_DENIED',

  // Queue errors
  QUEUE_FULL: 'QUEUE_FULL',
  JOB_NOT_FOUND: 'JOB_NOT_FOUND'
};
